### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by veerendra2** [veerendra2/ansible-role-prepare_dev_setup#7]
* Use [make](https://docs.ansible.com/ansible/latest/collections/community/general/make_module.html) module
* Add `autoremove`
  ```yaml
  - name: Run autoremove
    apt:
      autoremove: yes
    become: yes
  ```
